# NumPy tutorial

#### __Numerical Python (NumPy)__ --> provides support for large, multi-dimensional _arrays and matrices_, along with an extensive collection of _mathematical functions_ to operate on these arrays

##### _Commonly Used Functions_:
##### 1- __Array Creation:__ np.array(), np.zeros(), np.ones(), np.arange(), np.linspace()
##### 2- __Mathematical Functions:__ np.sum(), np.mean(), np.median(), np.std(), np.sqrt()
##### 3- __Linear Algebra:__ np.dot(), np.linalg.inv(), np.linalg.eig()
##### 4- __Random Number Generation:__ np.random.rand(), np.random.randint(), np.random.normal()
##### 5- __Reshaping and Flattening:__ np.reshape(), np.flatten()

### Array Creation

In [83]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", array)      # \n -> next line
print(type(array))

# Additional
from sympy import Matrix
matrix_form = Matrix(array)
matrix_form

Array:
 [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


Matrix([
[1, 2, 3],
[4, 5, 6]])

In [14]:
zeros_array = np.zeros(3)   
print("Zeros Array:\n", zeros_array)

Zeros Array:
 [0. 0. 0.]


In [ ]:
zeros_array = np.zeros((2, 3))   # (row, col)
print("Zeros Array:\n", zeros_array)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [154]:
ones_array = np.ones((2, 3))
print("Ones Array:\n", ones_array)

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [153]:
range_array = np.arange(0, 10, 2)      # from 0 to 10 with difference 2
print("Range Array:\n", range_array)

Range Array:
 [0 2 4 6 8]


In [ ]:
linspace_array = np.linspace(0, 5, 6)   # array of evenly spaced values over a specified interval.
print("Linspace Array:\n", linspace_array)

Linspace Array:
 [0. 1. 2. 3. 4. 5.]


### Mathematical Functions

In [22]:
array = np.array([1, 2, 3, 4, 5])
print(array)
print("Sum:", np.sum(array))
print("Mean:", np.mean(array))
print("Median:", np.median(array))
print("Standard Deviation:", np.std(array))
print("Square Root:", np.sqrt(array))

[1 2 3 4 5]
Sum: 15
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
# Exponential and Logarithmic Functions

array = np.array([1, 2, 3])
print("Exponential:", np.exp(array))
print("Natural Log:", np.log(array))
print("Log Base 10:", np.log10(array))
print("Log Base 2:", np.log2(array))

Exponential: [ 2.71828183  7.3890561  20.08553692]
Natural Log: [0.         0.69314718 1.09861229]
Log Base 10: [0.         0.30103    0.47712125]
Log Base 2: [0.        1.        1.5849625]


In [45]:
# Trigonometric Functions

angles = np.array([0, np.pi/2, np.pi])
print(angles)
print("Sine:", np.sin(angles))
print("Cosine:", np.cos(angles))
print("Tangent:", np.tan(angles))

# inverse trigonometric functions (sin, cos, tan).

values = np.array([0, 1, -1])
print("Arcsin:", np.arcsin(values))
print("Arccos:", np.arccos(values))
print("Arctan:", np.arctan(values))

[0.         1.57079633 3.14159265]
Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tangent: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
Arcsin: [ 0.          1.57079633 -1.57079633]
Arccos: [1.57079633 0.         3.14159265]
Arctan: [ 0.          0.78539816 -0.78539816]


### Linear Algebra
###### https://numpy.org/devdocs/reference/routines.linalg.html

In [27]:
# dot product of two arrays.

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print("Dot Product:", np.dot(array1, array2))

Dot Product: 32


In [31]:
# inverse of a square matrix.

matrix = np.array([[1, 2], [3, 4]])
print("Inverse:\n", np.linalg.inv(matrix))  # linalg -> linear Algebra

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [37]:
# eigenvalues and eigenvectors of a square matrix.

eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [38]:
determinant = np.linalg.det(matrix)
print("Determinant of Matrix:", determinant)

Determinant of Matrix: -2.0000000000000004


In [39]:
U, S, Vt = np.linalg.svd(matrix)
print("U:\n", U)
print("Singular Values:", S)
print("Vt:\n", Vt)

U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular Values: [5.4649857  0.36596619]
Vt:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [40]:
# norm (magnitude) of a vector or matrix

vector = np.array([3, 4])
norm = np.linalg.norm(vector)
print("Norm of Vector:", norm)

Norm of Vector: 5.0


In [41]:
# system of linear equations, 𝐴𝑥=𝑏

A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print("Solution for x:", x)

Solution for x: [2. 3.]


In [55]:
# Cholesky decomposition of a matrix (for positive definite matrices, returning a lower triangular matrix.)

positive_definite_matrix = np.array([[4, 2], [2, 3]])
cholesky_decomp = np.linalg.cholesky(positive_definite_matrix)
print("Cholesky Decomposition:\n", cholesky_decomp)

Cholesky Decomposition:
 [[2.         0.        ]
 [1.         1.41421356]]


In [56]:
matrix = np.array([[1, 2, 5], [3, 4, 6]])
rank = np.linalg.matrix_rank(matrix)
print("Rank of Matrix:", rank)

# QR decomposition, decomposing a matrix into an orthogonal matrix 𝑄 and an upper triangular matrix 𝑅

Q, R = np.linalg.qr(matrix)
print("Q:\n", Q)
print("R:\n", R)

# condition number of a matrix, which indicates the sensitivity of the solution of a system of equations to errors in the data. 
# A high condition number can indicate potential numerical instability.

condition_number = np.linalg.cond(matrix)
print("Condition Number of Matrix:", condition_number)

# trace of a matrix (sum of diagonal elements).

trace_value = np.trace(matrix)
print("Trace of Matrix:", trace_value)

Rank of Matrix: 2
Q:
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R:
 [[-3.16227766 -4.42718872 -7.27323862]
 [ 0.         -0.63245553 -2.84604989]]
Condition Number of Matrix: 7.318367990126654
Trace of Matrix: 5


In [58]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])
result = np.linalg.multi_dot([A, B, C])
print("Result of Multi-Dot Product:\n", result)

Result of Multi-Dot Product:
 [[ 413  454]
 [ 937 1030]]


In [59]:
vector1 = np.array([1, 2])
vector2 = np.array([3, 4])
outer_product = np.outer(vector1, vector2)
print("Outer Product:\n", outer_product)

inner_product = np.inner(vector1, vector2)
print("Inner Product:", inner_product)

kronecker_product = np.kron(A, B)
print("Kronecker Product:\n", kronecker_product)  # useful in tensor operations.

dot_product = np.dot(A, B)
print("Dot Product:\n", dot_product)


Outer Product:
 [[3 4]
 [6 8]]
Inner Product: 11
Kronecker Product:
 [[ 5  6 10 12]
 [ 7  8 14 16]
 [15 18 20 24]
 [21 24 28 32]]
Dot Product:
 [[19 22]
 [43 50]]


### Random Number Generation

In [46]:
rand_array = np.random.rand(2, 3)
print("Random Array (Uniform Distribution):\n", rand_array)

Random Array (Uniform Distribution):
 [[0.52452545 0.46119242 0.5565478 ]
 [0.13213144 0.4497723  0.84060943]]


In [51]:
randint_array = np.random.randint(0, 10, (2, 3))
print("Random Integer Array:\n", randint_array)

Random Integer Array:
 [[6 1 5]
 [0 6 0]]


In [52]:
normal_array = np.random.normal(0, 1, (2, 3))
print("Random Array (Normal Distribution):\n", normal_array)

Random Array (Normal Distribution):
 [[-0.47640319  0.99465834  0.80993663]
 [-0.42695143 -0.59625936  0.48084952]]


### Reshaping and Flattening

In [54]:
original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = original_array.reshape((2, 3))
print("Reshaped Array:\n", reshaped_array)

flattened_array = reshaped_array.flatten()
print("Flattened Array:", flattened_array)

Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]


## Some Basic about NumPy

In [118]:
# Creat NumPy 
import numpy as np

In [119]:
num1 = [1,2,3]
print(type(num1))

<class 'list'>


In [120]:
num1 = np.array(num1)
print(type(num1))

<class 'numpy.ndarray'>


In [121]:
num1

array([1, 2, 3])

In [122]:
num2 = [[1,2,3],[4,5,6]]  #2D array
print(type(num2))

<class 'list'>


In [123]:
num2 = np.array(num2)
print(type(num2))

<class 'numpy.ndarray'>


In [124]:
num2

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
num3 = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]] # 3D array
print(type(num3))

<class 'list'>


In [126]:
num3 = np.array(num3)
print(type(num3))

<class 'numpy.ndarray'>


In [127]:
num3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [128]:
num3.ndim  # dimension of array or matrix (3D array)

3

In [129]:
num2.ndim  # dimension of array or matrix (2D array)

2

In [130]:
num3.shape   # 2 row, 2 col, 3 dimension (3D)

(2, 2, 3)

In [131]:
num2.shape   # 2 rows, 3 colum

(2, 3)

In [132]:
num1.shape   # 2 rows, 1 colum

(3,)

In [133]:
num1.dtype  # numpy array store only same data type

dtype('int32')

In [134]:
nums = [1,4,7.8]

In [135]:
nums = np.array(nums)

In [136]:
nums.dtype

dtype('float64')

In [137]:
nums1 = [1,4,'hello']
print(type(nums1))

<class 'list'>


In [138]:
nums1 = np.array(nums1)
print(type(nums1))

<class 'numpy.ndarray'>


In [139]:
nums1.dtype

dtype('<U11')

### Create Arrays Using Numpy Functions 

In [140]:
import numpy as np

In [141]:
# zeros, ones, eye, diag, randint, rand, randn

In [144]:
arr1 = np.zeros(5) # 5rows, all zeros
arr1

array([0., 0., 0., 0., 0.])

In [145]:
arr2 = np.zeros((2,3)) #inter tuple, 2rows and 3colum
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [146]:
arr3 = np.ones((2,3)) 
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [147]:
arr4 = np.ones(4) 
arr4

array([1., 1., 1., 1.])

In [148]:
arr5 = np.eye(4) #2D matrix with dignal 1, 4rows and 4colum
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [149]:
arr6 = np.eye(3,4) # 3rows and 4colum
arr6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [155]:
np.diag(arr6) #to find diagnal

array([1., 1., 1.])

In [156]:
arr7 = np.diag([1,2,3,4]) #take list or array, 4*4matrix
arr7

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [158]:
rand_arr = np.random.randint(1,15,4) # 4 random int numbers from 1 to 14, pass 3 parameter
rand_arr

array([ 5, 12,  6,  3])

In [159]:
rand_arr1 = np.random.rand(4) # 4random any numbers from 0 to 1 (uniform distribution)
rand_arr1

array([0.16067669, 0.24296703, 0.8200136 , 0.51693573])

In [160]:
rand_arr2 = np.random.rand(2,3) # 2D array, 2rows and 3colum
rand_arr2

array([[0.07493042, 0.18194193, 0.41296945],
       [0.81505093, 0.07656695, 0.65465991]])

In [161]:
rand_arr3 = np.random.randn(4) # 4 random numbers 0 central (standard normal distribution), both -ive and +ive
rand_arr3

array([-0.03053112, -0.41851793, -0.28186756, -0.59406681])

In [164]:
rand_arr4 = np.random.rand(10) 
rand_arr4

array([0.63445489, 0.59955306, 0.93991716, 0.52825673, 0.11203219,
       0.32931385, 0.7970875 , 0.5111962 , 0.06377021, 0.09750006])

In [ ]:
np.mean(rand_arr4) # average

0.4613081850696049

## Reshaping data

In [166]:
import numpy as np

In [168]:
arrr = np.random.randint(1,100,10)  # 1 to 100, 10 int number
arrr

array([99, 46, 96, 29, 90,  5, 14, 22,  5, 80])

In [ ]:
arrr.ndim  # 1D array

1

In [171]:
arrr.shape #single 1D array with 20 elements, (10 row, 1 column)

(10,)

In [ ]:
arrr = np.random.randint(1,100,20)
arrr = arrr.reshape(2,10)  # reshaping mean changihng 1D into 2D or 3D or 2D into 1D array
arrr

array([[91,  7,  5, 75, 86, 63, 34, 47, 78, 99],
       [99, 26, 65, 54, 79, 23, 17, 14, 42, 53]])

In [174]:
arrr.shape  #2rows, 10colums

(2, 10)

In [175]:
arrr.ndim # 2D array

2

In [176]:
arrr = arrr.reshape(20) #again convert into 1D array
arrr

array([91,  7,  5, 75, 86, 63, 34, 47, 78, 99, 99, 26, 65, 54, 79, 23, 17,
       14, 42, 53])

In [177]:
arrr1 = np.random.randint(1,100,50)
arrr1 = arrr1.reshape(10,5)  #10rows, 5 colums
arrr1

array([[63, 66, 70, 44, 20],
       [24,  3, 77, 34, 89],
       [41, 56, 18,  6, 88],
       [82,  8, 50, 58,  6],
       [77, 12, 49, 10, 84],
       [43, 62,  3, 82, 68],
       [36, 67, 79, 87, 56],
       [25, 73, 60, 94, 54],
       [19, 87, 93, 95, 18],
       [89, 44, 58, 60,  1]])

In [178]:
arrr1.ndim

2

In [ ]:
arrr1 = arrr1.reshape(2,5,5) # 3D array
arrr1

array([[[63, 66, 70, 44, 20],
        [24,  3, 77, 34, 89],
        [41, 56, 18,  6, 88],
        [82,  8, 50, 58,  6],
        [77, 12, 49, 10, 84]],

       [[43, 62,  3, 82, 68],
        [36, 67, 79, 87, 56],
        [25, 73, 60, 94, 54],
        [19, 87, 93, 95, 18],
        [89, 44, 58, 60,  1]]])

In [180]:
arrr1.ndim

3

## -1 in reshape
##### --> jusr define row or column, other colunm and row adjust accordingly.  

In [181]:
import numpy as np

In [182]:
ar = np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [183]:
ar.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [184]:
ar.reshape(2,-1)  # numpy define yourself, in this case it should be 5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [186]:
ar.reshape(5,-1)  # 5rows and 2colums

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [187]:
ar1 = np.arange(1,111)  # from 1 to 110
ar1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110])

In [188]:
ar1.size

110

In [189]:
ar1.reshape(5,-1)  # (5,22)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22],
       [ 23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
         36,  37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59,  60,  61,  62,  63,  64,  65,  66],
       [ 67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  88],
       [ 89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110]])

## Seed Function

In [191]:
np.random.seed(123)        #  same random generate all time.
ary = np.random.randint(1,101,10)
ary

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48])

In [193]:
np.random.seed(12)  
ary1 = np.random.randint(1,101,10)
ary1

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

## Indexing And Slicing

In [195]:
arry = np.array([5,10,15,20,25])
arry

array([ 5, 10, 15, 20, 25])

In [196]:
arry[0] # indexing mean positing

5

In [197]:
arry[3]

20

In [198]:
arry[6]

IndexError: index 6 is out of bounds for axis 0 with size 5

In [199]:
arry[-1]  # last number

25

In [200]:
arry[-2]  # 2nd last

20

In [201]:
arry[-4]  # 4th last

10

In [202]:
arry

array([ 5, 10, 15, 20, 25])

In [ ]:
arry[0:2]   # from index 0 to (2-1)

array([ 5, 10])

In [ ]:
arry[1:]  # from index 1 to end

array([10, 15, 20, 25])

In [ ]:
arry[:3]  # from index start to (3-1)

array([ 5, 10, 15])

In [ ]:
arry
arry[1:-1]   # from index 0 to (last one-1)

array([10, 15, 20])

In [210]:
arry[:]  # whole array

array([ 5, 10, 15, 20, 25])

In [211]:
arry[0:5:2] # start:end:step

array([ 5, 15, 25])

In [212]:
arry[::-1]

array([25, 20, 15, 10,  5])

In [256]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]]) #2D array
print(matrix)
mat = Matrix(matrix)
mat

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


Matrix([
[ 5, 10, 15],
[20, 25, 30],
[35, 40, 45]])

In [221]:
matrix[0][1] #double brackets

10

In [222]:
matrix[1][2]

30

In [223]:
matrix[1,2] #single brackets

30

In [224]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [226]:
matrix[0:2,0:2]   # 0 to (2-1)    # slicing using single brackets

array([[ 5, 10],
       [20, 25]])

In [227]:
matrix[1:,1:]

array([[25, 30],
       [40, 45]])

In [228]:
matrix[1:2,1:2]    # (1,1)

array([[25]])

## View Vs Copy

In [229]:
Ara = np.array([5,10,15,20,25])
Ara

array([ 5, 10, 15, 20, 25])

In [230]:
Ara[0:2] = 0     # [0:n-1]
Ara

array([ 0,  0, 15, 20, 25])

In [231]:
sliced_arr = Ara[2:5] #sliced_arr is View of Ara
sliced_arr  

array([15, 20, 25])

In [232]:
sliced_arr[:] = 0
sliced_arr

array([0, 0, 0])

In [233]:
Ara  # zeros value in Ara also

array([0, 0, 0, 0, 0])

In [234]:
sliced_arr = Ara[2:5].copy()

In [235]:
sliced_arr[:] = 0
sliced_arr

array([0, 0, 0])

In [236]:
Ara

array([0, 0, 0, 0, 0])

## Conditional Selection 

In [237]:
ry = np.arange(1,11)
ry

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [241]:
ry < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [ ]:
ry[ry < 5]

array([1, 2, 3, 4])

In [239]:
ry < 8, 5 < ry

(array([ True,  True,  True,  True,  True,  True,  True, False, False,
        False]),
 array([False, False, False, False, False,  True,  True,  True,  True,
         True]))

In [242]:
mask = ry<5
ry[mask]   # element less then 5

array([1, 2, 3, 4])

In [243]:
ry[ry>5]

array([ 6,  7,  8,  9, 10])

In [244]:
ry[ry%2 == 0]

array([ 2,  4,  6,  8, 10])

In [245]:
ry[ry==5]

array([5])

In [246]:
ry[ry%2 == 0] = 0
ry

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

## Operations on array

In [247]:
n_arr = np.array([1,2,3,4])
n_arr

array([1, 2, 3, 4])

In [248]:
n_arr *2  # apply every element of array

array([2, 4, 6, 8])

In [249]:
n_arr

array([1, 2, 3, 4])

In [250]:
n_arr + 2

array([3, 4, 5, 6])

In [251]:
n_arr **2

array([ 1,  4,  9, 16])

In [255]:
n_arr = np.array([1,2,3,4]).reshape(2,2) #2D array
print(n_arr)
matrix = Matrix(n_arr)
matrix

[[1 2]
 [3 4]]


Matrix([
[1, 2],
[3, 4]])

In [257]:
n_arr *2

array([[2, 4],
       [6, 8]])

In [258]:
n_arr +2

array([[3, 4],
       [5, 6]])

In [259]:
n_arr **3

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [260]:
1/0

ZeroDivisionError: division by zero

In [261]:
n_arr/0  # warrning not error

C:\Users\03467132337\AppData\Local\Temp\ipykernel_5924\2323787849.py:1: RuntimeWarning: divide by zero encountered in divide
  n_arr/0  # warrning not error


array([[inf, inf],
       [inf, inf]])

In [ ]:
arr_1 = np.array([1,2,3,4])  # No. of element should be same
arr_2 = np.array([5,6,7,8])

In [263]:
arr_1 + arr_2

array([ 6,  8, 10, 12])

In [264]:
arr_1 * arr_2

array([ 5, 12, 21, 32])

In [265]:
arr_1 / arr_2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [266]:
arr_1 ** arr_2  # 1^5, 2^6,... --> corresponding elements

array([    1,    64,  2187, 65536])

In [267]:
arr_1 + arr_1

array([2, 4, 6, 8])

In [268]:
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])
arr_3 = np.array([9,10,11,12])

In [269]:
arr_1 * arr_2 + arr_3

array([14, 22, 32, 44])

In [270]:
arr_1 * arr_2 / arr_3

array([0.55555556, 1.2       , 1.90909091, 2.66666667])

In [ ]:
np.random.seed(123)
matrix1 = np.random.randint(1,12,9).reshape(3,3)  # shape sohuld be same
matrix2 = np.random.randint(5,15,9).reshape(3,3)

In [274]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [275]:
matrix2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [276]:
mat1 = Matrix(matrix1)
mat1

Matrix([
[ 3, 3,  7],
[ 2, 4, 11],
[10, 7,  2]])

In [277]:
mat2 = Matrix(matrix2)
mat2

Matrix([
[5, 6, 14],
[5, 5, 14],
[8, 9,  5]])

In [278]:
matrix1 + matrix2

array([[ 8,  9, 21],
       [ 7,  9, 25],
       [18, 16,  7]])

In [279]:
matrix1 * matrix2 # wrong multiplication

array([[ 15,  18,  98],
       [ 10,  20, 154],
       [ 80,  63,  10]])

In [280]:
matrix1.dot(matrix2)   # right multiplication

array([[ 86,  96, 119],
       [118, 131, 139],
       [101, 113, 248]])

## numpy functions

In [281]:
narr = np.array([2,80,1,97,5])
narr

array([ 2, 80,  1, 97,  5])

In [282]:
np.min(narr)

1

In [283]:
np.max(narr)

97

In [284]:
np.argmin(narr) # minimum number position

2

In [286]:
np.argmax(narr) # maximum number position

3

In [287]:
np.sqrt(narr)

array([1.41421356, 8.94427191, 1.        , 9.8488578 , 2.23606798])

In [288]:
np.exp(narr)

array([7.38905610e+00, 5.54062238e+34, 2.71828183e+00, 1.33833472e+42,
       1.48413159e+02])

In [289]:
np.sin(narr)

array([ 0.90929743, -0.99388865,  0.84147098,  0.37960774, -0.95892427])

In [290]:
np.cos(narr)

array([-0.41614684, -0.11038724,  0.54030231, -0.92514754,  0.28366219])

In [291]:
np.linspace(1,15,50) # from 1 t0 15, 50 equaly distributed number 

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [293]:
np.linspace(1,50,6)

array([ 1. , 10.8, 20.6, 30.4, 40.2, 50. ])

In [294]:
new_arr = np.array([1,2,3,0],dtype='bool')
new_arr

array([ True,  True,  True, False])

In [295]:
for i in new_arr:
    print(i)

True
True
True
False


## NumPy Axis 

In [296]:
import numpy as np

In [297]:
np.random.seed(123)
matri = np.random.randint(1,11,9).reshape(3,3)
matri

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [298]:
np.sum(matri)

39

In [299]:
matri.sum()

39

In [300]:
np.min(matri)

1

In [301]:
np.max(matri)

10

In [302]:
np.min(matri, axis=1) #find minimum in each row

array([3, 2, 1])

In [303]:
np.min(matri, axis=0) #find minimum in each colum

array([2, 2, 1])

In [304]:
np.sum(matri, axis=0)

array([12,  9, 18])

In [305]:
matri

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [306]:
mat3 = Matrix(matri)
mat3

Matrix([
[3, 3,  7],
[2, 4, 10],
[7, 2,  1]])

In [307]:
np.cumsum(matri)  #cumulative sum

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39])

In [308]:
np.cumsum(matri, axis=1)  #cumulative sum, rows vise

array([[ 3,  6, 13],
       [ 2,  6, 16],
       [ 7,  9, 10]])

In [309]:
np.prod(matri, axis=0)  #product

array([42, 24, 70])

## shuffle and unique `

In [310]:
import numpy as np

In [311]:
np.random.seed(123)
aryy = np.random.randint(1,15,15)
aryy

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [312]:
np.random.shuffle(aryy)
aryy

array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [313]:
np.unique(aryy)  #give unique element means no repition 

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [314]:
np.unique(aryy).size

10

In [315]:
np.unique(aryy, return_index=True, return_counts=True) 
# give three arrays, 1.unique array, 2.position of elements, 3.No. of elements

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([ 8,  1,  6,  0,  7, 12,  2,  3,  4, 14], dtype=int64),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1], dtype=int64))

## Horizontal and Vertical Stacking

In [316]:
np.random.seed(123)
matr1 = np.random.randint(1,20,9).reshape(3,3)
matr2 = np.random.randint(20,40,9).reshape(3,3)

In [317]:
matr1

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [318]:
matr2

array([[35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [ ]:
m1 = np.hstack((matr1,matr2)) # horizontal cancatination of two matrixs

M1 = Matrix(m1)
M1

Matrix([
[14,  3,  3, 35, 29, 20],
[ 7, 18, 11, 34, 20, 35],
[ 2,  1, 18, 39, 34, 24]])

In [320]:
m2 = np.vstack((matr1,matr2)) #vertical cancatination of two matrixs

M2 = Matrix(m2)
M2

Matrix([
[14,  3,  3],
[ 7, 18, 11],
[ 2,  1, 18],
[35, 29, 20],
[34, 20, 35],
[39, 34, 24]])

In [321]:
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])

In [322]:
np.hstack((ar1,ar2))

array([1, 2, 3, 4, 5, 6])

In [323]:
np.vstack((ar1,ar2))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
ar1 = np.array([[1, 2, 3], [4, 5, 6]])
ar2 = np.array([[7, 8, 9], [10, 11, 12]])

# Horizontal stacking
hstacked = np.hstack((ar1, ar2))
hmatrix = Matrix(hstacked)
hmatrix


Matrix([
[1, 2, 3,  7,  8,  9],
[4, 5, 6, 10, 11, 12]])

In [330]:
#  Vertical stacking
vstacked = np.vstack((ar1, ar2))
vmatrix = Matrix(vstacked)
vmatrix

Matrix([
[ 1,  2,  3],
[ 4,  5,  6],
[ 7,  8,  9],
[10, 11, 12]])

In [334]:
ar1 = np.array([[1, 2, 3], [4, 5, 6]])
ar2 = np.array([[7, 8, 9], [10, 11, 12]])

Matr1 = Matrix(ar1)
Matr1

Matrix([
[1, 2, 3],
[4, 5, 6]])

In [335]:
Matr2 = Matrix(ar2)
Matr2

Matrix([
[ 7,  8,  9],
[10, 11, 12]])

In [ ]:
# Use np.block to combine the arrays in a custom structure
block_array = np.block([[ar1, ar2],    # First row: ar1 and ar2 horizontally
                         [ar1, ar2]])   # Second row: ar1 and ar2 horizontally
bmatrix = Matrix(block_array)
bmatrix

Matrix([
[ 1,  2,  3,  1,  2,  3],
[ 4,  5,  6,  4,  5,  6],
[ 7,  8,  9,  7,  8,  9],
[10, 11, 12, 10, 11, 12]])

In [ ]:
# Define example matrices A, B, C, D
A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

C = np.array([[9, 10], 
              [11, 12]])

D = np.array([[13, 14], 
              [15, 16]])


In [339]:
# Arrange the matrices in a block structure
block_matrix = np.block([[A, B], 
                          [C, D]])
bmatri = Matrix(block_matrix)
bmatri


Matrix([
[ 1,  2,  5,  6],
[ 3,  4,  7,  8],
[ 9, 10, 13, 14],
[11, 12, 15, 16]])

In [344]:
from sympy import Matrix, latex

# Define the matrices A, B, C, D
A = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12], 
              [13, 14, 15, 16]])

B = np.array([[17], 
              [18], 
              [19], 
              [20]])

C = np.array([[21, 22, 23, 24]])

D = np.array([[25]])

# Use np.block to combine the matrices
block_matrix = np.block([[A, B], 
                          [C, D]])

hello_M = Matrix(block_matrix)
hello_M

# bmatri1 = Matrix(block_matrix)
# bmatri1


Matrix([
[ 1,  2,  3,  4, 17],
[ 5,  6,  7,  8, 18],
[ 9, 10, 11, 12, 19],
[13, 14, 15, 16, 20],
[21, 22, 23, 24, 25]])

## The End