# NumPy tutorial
Harshit youtube Channel

## Creat NumPy 

In [2]:
import numpy as np

In [24]:
num1 = [1,2,3]

In [25]:
num1 = np.array(num1)

In [26]:
num1

array([1, 2, 3])

In [10]:
num2 = [[1,2,3],[4,5,6]]  #2D array

In [11]:
num2 = np.array(num2)

In [12]:
num2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
num3 = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]] # 3D array

In [14]:
num3 = np.array(num3)

In [15]:
num3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [18]:
num3.ndim

3

In [19]:
num2.ndim

2

In [21]:
num3.shape

(2, 2, 3)

In [22]:
num2.shape   # 2 rows, 3 colum

(2, 3)

In [27]:
num1.shape

(3,)

In [28]:
num1.dtype  # numpy array store only same data type

dtype('int32')

In [32]:
nums = [1,4,7.8]

In [33]:
nums = np.array(nums)

In [34]:
nums.dtype

dtype('float64')

In [35]:
nums1 = [1,4,'hello']

In [36]:
nums1 = np.array(nums1)

In [38]:
nums1.dtype

dtype('<U11')

## Create Arrays Using Numpy Functions 

In [39]:
import numpy as np

In [40]:
# zeros, ones, eye, diag, randint, rand, randn

In [41]:
arr1 = np.zeros(5) # 5rows, all zeros
arr1

array([0., 0., 0., 0., 0.])

In [43]:
arr2 = np.zeros((2,3)) #inter tuple, 2rows and 3colum
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
arr3 = np.ones((2,3)) 
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
arr4 = np.ones(4) 
arr4

array([1., 1., 1., 1.])

In [47]:
arr5 = np.eye(4) #2D matrix with dignal 1, 4rows and 4colum
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
arr6 = np.eye(3,4) # 3rows and 4colum
arr6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [51]:
np.diag(arr6) #to find diagnal

array([1., 1., 1.])

In [50]:
arr7 = np.diag([1,2,3,4]) #take list or array, 4*4matrix
arr7

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [56]:
rand_arr = np.random.randint(1,15,4) #4random numbers from 1 to 14, pass 3 parameter
rand_arr

array([13,  5,  4,  9])

In [57]:
rand_arr1 = np.random.rand(4) #4random numbers from 0 to 1 (uniform distribution)
rand_arr1

array([0.92267673, 0.82877509, 0.82903947, 0.1030578 ])

In [58]:
rand_arr2 = np.random.rand(2,3) #2D array, 2rows and 3colum
rand_arr2

array([[0.55015474, 0.80728104, 0.39878537],
       [0.81986049, 0.7208922 , 0.85714944]])

In [59]:
rand_arr3 = np.random.randn(4) #4random numbers 0 central (standard normal distribution), both -ive and +ive
rand_arr3

array([ 0.99881726, -0.336342  ,  0.19332473,  1.33476427])

In [61]:
rand_arr4 = np.random.rand(20) 
rand_arr4

array([0.77899559, 0.78883757, 0.03480298, 0.21094683, 0.92120185,
       0.77161337, 0.12584386, 0.71672372, 0.01994929, 0.52855997,
       0.73786345, 0.16144746, 0.8600788 , 0.63490078, 0.35953838,
       0.33606648, 0.20330576, 0.69191773, 0.62470022, 0.10224645])

In [62]:
np.mean(rand_arr4) #average

0.4804770268941758

## Reshaping data

In [63]:
import numpy as np

In [64]:
arrr = np.random.randint(1,100,20)
arrr

array([26, 11, 21, 72, 12, 71, 27, 22, 82,  7, 60, 92, 44, 29, 75, 92, 87,
       35, 95, 28])

In [65]:
arrr.ndim  #1D array

1

In [66]:
arrr.shape #single 1D array with 20 elements,

(20,)

In [68]:
arrr = np.random.randint(1,100,20)
arrr = arrr.reshape(2,10)  #reshaping mean changihng 1D into 2D or 3D or 2D into 1D array
arrr

array([[92, 54, 15, 29, 64, 27, 29, 65, 52, 25],
       [50, 26, 71, 26, 27, 95, 57, 26, 25, 82]])

In [69]:
arrr.shape  #2rows, 10colums

(2, 10)

In [70]:
arrr.ndim #2D array

2

In [72]:
arrr = arrr.reshape(20) #again convert into 1D array
arrr

array([92, 54, 15, 29, 64, 27, 29, 65, 52, 25, 50, 26, 71, 26, 27, 95, 57,
       26, 25, 82])

In [73]:
arrr1 = np.random.randint(1,100,50)
arrr1 = arrr1.reshape(10,5)  #10rows, 5 colums
arrr1

array([[15, 53, 80, 78,  7],
       [33, 55, 16, 83, 79],
       [14, 52, 80,  2, 57],
       [98, 77, 24, 33, 72],
       [ 3, 15, 82, 13, 10],
       [78,  3, 15, 80, 24],
       [61, 46, 87, 59,  3],
       [ 7, 67, 58, 73, 44],
       [97, 21, 74,  3, 41],
       [37, 37, 49, 91, 21]])

In [74]:
arrr1.ndim

2

In [76]:
arrr1 = arrr1.reshape(2,5,5) #3D array
arrr1

array([[[15, 53, 80, 78,  7],
        [33, 55, 16, 83, 79],
        [14, 52, 80,  2, 57],
        [98, 77, 24, 33, 72],
        [ 3, 15, 82, 13, 10]],

       [[78,  3, 15, 80, 24],
        [61, 46, 87, 59,  3],
        [ 7, 67, 58, 73, 44],
        [97, 21, 74,  3, 41],
        [37, 37, 49, 91, 21]]])

In [77]:
arrr1.ndim

3

## -1 in reshape

In [5]:
import numpy as np

In [7]:
ar = np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
ar.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
ar.reshape(2,-1)  #numpy define yourself, in this case it should be 5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
ar.reshape(5,-1)  #5rows and 2colums

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
ar1 = np.arange(1,111)
ar1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110])

In [19]:
ar1.size

110

In [20]:
ar1.reshape(5,-1)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22],
       [ 23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
         36,  37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59,  60,  61,  62,  63,  64,  65,  66],
       [ 67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  88],
       [ 89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110]])

## Seed Function

In [21]:
np.random.seed(123)  #same random generate all time.
ary = np.random.randint(1,101,10)
ary

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48])

In [22]:
np.random.seed(12)  
ary1 = np.random.randint(1,101,10)
ary1

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

## Indexing And Slicing

In [23]:
arry = np.array([5,10,15,20,25])
arry

array([ 5, 10, 15, 20, 25])

In [24]:
arry[0] #indexing mean positing

5

In [25]:
arry[3]

20

In [26]:
arry[6]

IndexError: index 6 is out of bounds for axis 0 with size 5

In [28]:
arry[-1] #last number

25

In [29]:
arry[-4]

10

In [30]:
arry

array([ 5, 10, 15, 20, 25])

In [31]:
arry[0:2]

array([ 5, 10])

In [32]:
arry[1:]

array([10, 15, 20, 25])

In [34]:
arry[:3]

array([ 5, 10, 15])

In [35]:
arry[1:-1]

array([10, 15, 20])

In [36]:
arry[:] #whole array

array([ 5, 10, 15, 20, 25])

In [37]:
arry[0:5:2] #start:end:step

array([ 5, 15, 25])

In [38]:
arry[::-1]

array([25, 20, 15, 10,  5])

In [39]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]]) #2D array
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
matrix[0][1] #double brackets

10

In [41]:
matrix[1][2]

30

In [43]:
matrix[1,2] #single brackets

30

In [44]:
matrix[0:2,0:2]       #slicing using single brackets

array([[ 5, 10],
       [20, 25]])

In [45]:
matrix[1:,1:]

array([[25, 30],
       [40, 45]])

In [46]:
matrix[1:2,1:2]

array([[25]])

## View Vs Copy

In [59]:
Ara = np.array([5,10,15,20,25])
Ara

array([ 5, 10, 15, 20, 25])

In [48]:
Ara[0:2] = 0
Ara

array([ 0,  0, 15, 20, 25])

In [51]:
sliced_arr = Ara[2:5] #sliced_arr is View of Ara
sliced_arr  

array([15, 20, 25])

In [52]:
sliced_arr[:] = 0
sliced_arr

array([0, 0, 0])

In [54]:
Ara #zeros value in Ara also

array([ 5, 10,  0,  0,  0])

In [60]:
sliced_arr = Ara[2:5].copy()

In [61]:
sliced_arr[:] = 0
sliced_arr

array([0, 0, 0])

In [62]:
Ara

array([ 5, 10, 15, 20, 25])

## Conditional Selection 

In [63]:
ry = np.arange(1,11)
ry

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
ry < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [68]:
ry < 8, 5 < ry

(array([ True,  True,  True,  True,  True,  True,  True, False, False,
        False]),
 array([False, False, False, False, False,  True,  True,  True,  True,
         True]))

In [71]:
mask = ry<5
ry[mask]   #element less then 5

array([1, 2, 3, 4])

In [72]:
ry[ry>5]

array([ 6,  7,  8,  9, 10])

In [73]:
ry[ry%2 == 0]

array([ 2,  4,  6,  8, 10])

In [76]:
ry[ry==5]

array([5])

In [77]:
ry[ry%2 == 0] = 0
ry

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

## Operations on array

In [79]:
n_arr = np.array([1,2,3,4])
n_arr

array([1, 2, 3, 4])

In [80]:
n_arr *2 #apply every element of array

array([2, 4, 6, 8])

In [81]:
n_arr

array([1, 2, 3, 4])

In [82]:
n_arr + 2

array([3, 4, 5, 6])

In [83]:
n_arr **2

array([ 1,  4,  9, 16], dtype=int32)

In [84]:
n_arr = np.array([1,2,3,4]).reshape(2,2) #2D array
n_arr

array([[1, 2],
       [3, 4]])

In [85]:
n_arr *2

array([[2, 4],
       [6, 8]])

In [86]:
n_arr +2

array([[3, 4],
       [5, 6]])

In [87]:
n_arr **3

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [88]:
1/0

ZeroDivisionError: division by zero

In [89]:
n_arr/0 #warrning not error

C:\Users\Dell\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf],
       [inf, inf]])

In [91]:
arr_1 = np.array([1,2,3,4])  #No. of element should be same
arr_2 = np.array([5,6,7,8])

In [92]:
arr_1 + arr_2

array([ 6,  8, 10, 12])

In [93]:
arr_1 * arr_2

array([ 5, 12, 21, 32])

In [94]:
arr_1 / arr_2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [95]:
arr_1 ** arr_2  #1^5, 2^6,...

array([    1,    64,  2187, 65536], dtype=int32)

In [96]:
arr_1 + arr_1

array([2, 4, 6, 8])

In [97]:
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])
arr_3 = np.array([9,10,11,12])

In [98]:
arr_1 * arr_2 + arr_3

array([14, 22, 32, 44])

In [99]:
arr_1 * arr_2 / arr_3

array([0.55555556, 1.2       , 1.90909091, 2.66666667])

In [100]:
np.random.seed(123)
matrix1 = np.random.randint(1,12,9).reshape(3,3) #shape sohuld be same
matrix2 = np.random.randint(5,15,9).reshape(3,3)

In [101]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [102]:
matrix2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [105]:
matrix1 + matrix2

array([[ 8,  9, 21],
       [ 7,  9, 25],
       [18, 16,  7]])

In [106]:
matrix1 * matrix2 #wrong multiplication

array([[ 15,  18,  98],
       [ 10,  20, 154],
       [ 80,  63,  10]])

In [107]:
matrix1.dot(matrix2) #right multiplication

array([[ 86,  96, 119],
       [118, 131, 139],
       [101, 113, 248]])

## numpy functions

In [108]:
narr = np.array([2,80,1,97,5])
narr

array([ 2, 80,  1, 97,  5])

In [109]:
np.min(narr)

1

In [110]:
np.max(narr)

97

In [111]:
np.argmin(narr) # minimum number position

2

In [112]:
np.argmax(narr)

3

In [113]:
np.sqrt(narr)

array([1.41421356, 8.94427191, 1.        , 9.8488578 , 2.23606798])

In [114]:
np.exp(narr)

array([7.38905610e+00, 5.54062238e+34, 2.71828183e+00, 1.33833472e+42,
       1.48413159e+02])

In [115]:
np.sin(narr)

array([ 0.90929743, -0.99388865,  0.84147098,  0.37960774, -0.95892427])

In [116]:
np.cos(narr)

array([-0.41614684, -0.11038724,  0.54030231, -0.92514754,  0.28366219])

In [119]:
np.linspace(1,15,50) # from 1 t0 15, 50 equaly distributed number 

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [120]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [123]:
new_arr = np.array([1,2,3,0],dtype='bool')
new_arr

array([ True,  True,  True, False])

In [124]:
for i in new_arr:
    print(i)

True
True
True
False


## NumPy Axis 

In [2]:
import numpy as np

In [3]:
np.random.seed(123)
matri = np.random.randint(1,11,9).reshape(3,3)
matri

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [4]:
np.sum(matri)

39

In [5]:
matri.sum()

39

In [6]:
np.min(matri)

1

In [7]:
np.max(matri)

10

In [8]:
np.min(matri, axis=1) #find minimum in each row

array([3, 2, 1])

In [9]:
np.min(matri, axis=0) #find minimum in each colum

array([2, 2, 1])

In [10]:
np.sum(matri, axis=0)

array([12,  9, 18])

In [11]:
matri

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [12]:
np.cumsum(matri)  #cumulative sum

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39], dtype=int32)

In [13]:
np.cumsum(matri, axis=1)  #cumulative sum, rows vise

array([[ 3,  6, 13],
       [ 2,  6, 16],
       [ 7,  9, 10]], dtype=int32)

In [14]:
np.prod(matri, axis=0)  #product

array([42, 24, 70])

## shuffle and unique `

In [21]:
import numpy as np

In [23]:
np.random.seed(123)
aryy = np.random.randint(1,15,15)
aryy

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [25]:
np.random.shuffle(aryy)
aryy

array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [27]:
np.unique(aryy)  #give unique element means no repition 

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [28]:
np.unique(aryy).size

10

In [29]:
np.unique(aryy, return_index=True, return_counts=True) 
#give three arrays, 1.unique array, 2.position of elements, 3.No. of elements

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([ 8,  1,  6,  0,  7, 12,  2,  3,  4, 14], dtype=int64),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1], dtype=int64))

## Horizontal and Vertical Stacking

In [30]:
np.random.seed(123)
matr1 = np.random.randint(1,20,9).reshape(3,3)
matr2 = np.random.randint(20,40,9).reshape(3,3)

In [31]:
matr1

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [32]:
matr2

array([[35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [33]:
np.hstack((matr1,matr2)) #horizontal cancatination of two matrixs

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [34]:
np.vstack((matr1,matr2)) #vertical cancatination of two matrixs

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [35]:
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])

In [36]:
np.hstack((ar1,ar2))

array([1, 2, 3, 4, 5, 6])

In [38]:
np.vstack((ar1,ar2))

array([[1, 2, 3],
       [4, 5, 6]])

## The End